version: '2'
services:
    hipster-app:
        image: hipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hipster-mysql:3306/hipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hipster-elasticsearch:9300
        ports:
            - 8080:8080
    hipster-mysql:
        extends:
            file: mysql.yml
            service: hipster-mysql
    hipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hipster-elasticsearch
